### PR TITLE
HAN-138: Agregar endpoint para obtener usuarios con filtro por nickname

### PR DESCRIPTION
**Pull request by violetaperezandrade**

### CODE REVIEW

**Comment by violetaperezandrade** [comment]
> ## [Codecov](https://app.codecov.io/gh/Hanagotchi/users/pull/25?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi) Report
> Attention: Patch coverage is `66.66667%` with `4 lines` in your changes are missing coverage. Please review.
> 
> [Flag](https://app.codecov.io/gh/Hanagotchi/users/pull/25/flags?src=pr&el=flags&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi)	Coverage Δ	
> [unittests](https://app.codecov.io/gh/Hanagotchi/users/pull/25/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi)	`76.14% <66.66%> (?)`	
> Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi#carryforward-flags-in-the-pull-request-comment) to find out more.
> 
> [Files](https://app.codecov.io/gh/Hanagotchi/users/pull/25?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi)	Coverage Δ	
> [app/service/Users.py](https://app.codecov.io/gh/Hanagotchi/users/pull/25?src=pr&el=tree&filepath=app%2Fservice%2FUsers.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Hanagotchi#diff-YXBwL3NlcnZpY2UvVXNlcnMucHk=)	`76.14% <66.66%> (ø)`

image

**Review by Agustinefe — APPROVED** [review]
Excelenchi 🚀 🚀

**Review by Agustinefe — CHANGES_REQUESTED** [review]
Cuando llamo a social/users/followers con estos parametros
image

Me tira un 500. Esto es lo que me devuelve el traceback:
image
El id le esta llegando bien a la funcion del servicio, asi que debe haber algun quilombito con el async.

Por otra parte, creo que no seria mas necesario el campo query en este endpoint (que si era y es necesario en el otro endpoint que hiciste (que anda bien)).

**Review by Agustinefe — APPROVED** [review]
Silly me, flashe

**Pull request merged**
